miningapp/urls.py
from django.urls import path
from . import views
from .views import PasswordsChangeView

app_name='mining'
urlpatterns = [
    # Page urls and paths
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('reviews/', views.reviews, name='reviews'),
    path('team/', views.team, name='team'),
    path('tac/', views.tac, name='tac'),
    path('plans/', views.plans, name='plans'),
    path('account/', views.account, name='account'),
    path('account/login/', views.login, name='login'),
    path('account/logout/', views.logout, name='logout'),
    path('account/register/', views.register, name='register'),
    path('account/register/<str:refcode>/', views.uplineRegister, name='upline_register'),
    path('account/mining-history/',views.investHistory, name='invest_history'),
    path('account/mining/<str:investment_id>/',views.investmentDetail, name='investment_detail'),
    path('account/withdrawal-history/', views.withdrawalHistory, name='withdrawal_history'),
    path('account/withdraw/', views.withdrawalAssets, name='withdraw'),
    path('account/invest/', views.createInvest, name='invest'),
    path('account/invest/invoice/<str:investment_id>/', views.invoice, name='invoice'),
    path('account/profile/', views.profile, name='profile'),
    path('account/affiliates/', views.affiliates, name='affiliates'),
    path('account/notifications/', views.notifications, name='notifications'),
    path('account/change-password/', PasswordsChangeView.as_view(template_name="change_password.html")),
    path('account/change-password/success/', views.passwordChangeSuccess, name="password_change_success"),

    # Pseudo views
    path('process_investment/', views.processInvestment, name='process_investment'),
    path('invest_from_balance/', views.investFromBalance, name='invest_from_balance'),
    path('confirm_payment/', views.confirmPayment, name='confirm_payment'),
    path('investment-pdf/<str:investment_id>/', views.investmentPDF, name='investment_pdf'),
]

miningsite/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import handler404
# For password reset
from django.contrib.auth import views as auth_views

# Default admin site settings
admin.site.site_title = "Mining Admin"
admin.site.site_header = "MINING ADMIN"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miningapp.urls')),


    # Password reset paths
    # Don't use reset paths under namespaced url
    # or better still use in projects url 
    
    path('reset-password/', 
    auth_views.PasswordResetView.as_view(
    template_name="password_reset.html",
    success_url=reverse_lazy('password_reset_done')
    ), 
    name="reset_password"),

    path('reset-password-sent/', 
    auth_views.PasswordResetDoneView.as_view(
    template_name="password_reset_sent.html"
    ), 
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(
    template_name="password_reset_form.html",
    success_url=reverse_lazy('password_reset_complete')
    ), 
    name="password_reset_confirm"),

    path('password-reset-complete', 
    auth_views.PasswordResetCompleteView.as_view(
    template_name="password_reset_complete.html"
    ), 
    name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# Error page settings
handler404 = 'miningapp.views.error404'
handler500 = 'miningapp.views.error500'

templates/change_password.html
{% extends 'dashboardbase.html' %}
{% load static %}

{% block title %}
<title>Change password | {{company.name}}</title>
{% endblock %}

{% block pagetitle %}
<div class="row">
    <div class="col-md-12 m-b-30">
        <!-- begin page title -->
        <div class="d-block d-lg-flex flex-nowrap align-items-center">
            <div class="page-title mr-4 pr-4 border-right">
                <h1>Change Password</h1>
            </div>
            <div class="breadcrumb-bar align-items-center">
                <nav>
                    <ol class="breadcrumb p-0 m-b-0">
                        <li class="breadcrumb-item">
                            <a href="#"><i class="ti ti-home"></i></a>
                        </li>
                        <li class="breadcrumb-item">
                            Password update
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- end page title -->
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card card-statistics">
            <div class="card-body p-0">
                <div class="row no-gutters">
                    <div class="col-xl-6 col-md-6 col-12 border-t border-right">
                        <div class="page-account-form">
                            <div class="form-titel border-bottom p-3">
                                <h4 class="mb-0 py-2">Update password</h4>
                            </div>
                            <div class="p-4">
                                <form method="post" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        {{form.as_p}}
                                    </div>
                                    <button class="btn btn-primary mt-20">Update Password</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/email_congrats.html
<!DOCTYPE html PUBLIC>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
  <meta name='viewport' content='width=320, initial-scale=1' />
  <title>{{company.site_domain}}</title>
  <style type='text/css'>

    /* ----- Client Fixes ----- */

    /* Force Outlook to provide a 'view in browser' message */
    #outlook a {
      padding: 0;
    }

    /* Force Hotmail to display emails at full width */
    .ReadMsgBody {
      width: 100%;
    }

    .ExternalClass {
      width: 100%;
    }

    /* Force Hotmail to display normal line spacing */
    .ExternalClass,
    .ExternalClass p,
    .ExternalClass span,
    .ExternalClass font,
    .ExternalClass td,
    .ExternalClass div {
      line-height: 100%;
    }


     /* Prevent WebKit and Windows mobile changing default text sizes */
    body, table, td, p, a, li, blockquote {
      -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
    }


    /* Allow smoother rendering of resized image in Internet Explorer */
    img {
      -ms-interpolation-mode: bicubic;
    }

     /* ----- Reset ----- */

    html,
    body,
    .body-wrap,
    .body-wrap-cell {
      margin: 0;
      padding: 0;
      background: #ffffff;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 14px;
      color: #464646;
      text-align: left;
    }

    img {
      border: 0;
      line-height: 100%;
      outline: none;
      text-decoration: none;
    }

    table {
      border-collapse: collapse !important;
    }

    td, th {
      text-align: left;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 14px;
      color: #464646;
      line-height:1.5em;
    }

    b a,
    .footer a {
      text-decoration: none;
      color: #464646;
    }

    a.blue-link {
      color: blue;
      text-decoration: underline;
    }

    /* ----- General ----- */

    td.center {
      text-align: center;
    }

    .left {
      text-align: left;
    }

    .body-padding {
      padding: 24px 40px 40px;
    }

    .border-bottom {
      border-bottom: 1px solid #D8D8D8;
    }

    table.full-width-gmail-android {
      width: 100% !important;
    }


    /* ----- Header ----- */
    .header {
      font-weight: bold;
      font-size: 16px;
      line-height: 16px;
      height: 16px;
      padding-top: 19px;
      padding-bottom: 7px;
      background: #040c22;
    }

    .header a {
      color: #040c22;
      text-decoration: none;
    }

    .header h3 {
      text-transform: uppercase;
    }

    /* ----- Footer ----- */

    .footer a {
      font-size: 12px;
    }
  </style>

  <style type='text/css' media='only screen and (max-width: 650px)'>
    @media only screen and (max-width: 650px) {
      * {
        font-size: 16px !important;
      }

      table[class*='w320'] {
        width: 320px !important;
      }

      td[class='mobile-center'],
      div[class='mobile-center'] {
        text-align: center !important;
      }

      td[class*='body-padding'] {
        padding: 20px !important;
      }

      td[class='mobile'] {
        text-align: right;
        vertical-align: top;
      }
    }
  </style>

</head>
<body style='padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none'>
<table border='0' cellpadding='0' cellspacing='0' width='100%'>
<tr>
 <td valign='top' align='left' width='100%'>
 <center>
 
   <table class='w320 full-width-gmail-android' bgcolor='#f9f8f8' style='background-color:transparent' cellpadding='0' cellspacing='0' border='0' width='4%'>
      <tr>
        <td width='100%' height='40' valign='top'>
              <table class='full-width-gmail-android' cellspacing='0' cellpadding='0' border='0' width='100%'>
                <tr>
                  <td class='header center' width='100%'>
                    {% if company.logo %}
                    <img src='{{company.logo.url}}' width='50px;'><br>
                    {% elif company.name %}
                    <h3>{{company.name}}</h3>
                    {% else %}
                    <h3>{{company.site_domain}}</h3>
                    {% endif %}
                  </td>
                </tr>
              </table>
            <!--[if gte mso 9]>
              </v:textbox>
            </v:rect>
            <![endif]-->
        </td>
      </tr>
    </table>

    <table cellspacing='0' cellpadding='0' width='100%' bgcolor='#ffffff'>
      <tr>
        <td align='center'>
          <center>
            <table class='w320' cellspacing='0' cellpadding='0' width='500'>
              <tr>
                <td class='body-padding mobile-padding'>

                <table cellpadding='0' cellspacing='0' width='100%'>
                  <tr>
                    <td style='text-align:center; font-size:30px; padding-bottom:20px;'>
                     Congratulations...  Mining package has successfully completed
                    </td>
                  </tr>
                  <tr>
                    <td style='padding-bottom:20px;'>
                     Congrats {{investment.user.first_name}}, your mining package of {{investment.amount}} has successfully been completed and returns have been accumulated on your balance.
                    </td>
                  </tr>
                </table>

                <table cellspacing='0' cellpadding='0' width='100%'>
                  <tr>
                    <td>
                      <b>Security Tips: Remember to keep your password safe as we will never request for your password!</b>
                    </td>
                   </tr>
                  <tr>
                    <td class='border-bottom' height='5'></td>
                    <td class='border-bottom' height='5'></td>
                  </tr>
                  <tr>
                    <td style='padding-top:5px; vertical-align:top;'>
                     * Never give your login access to anyone<br>
                     * Contact our support at <a href='MailTo:{{company.email}}'>{{company.email}} </a> if you need any assistance<br>
                     <b>Enjoy your journey {{investment.user.first_name}}</b>
                    </td>
                  </tr>
                </table>

                
                <table cellspacing='0' cellpadding='0' width='100%'>
                  <tr>
                    <td class='left' style='text-align:left;'>
                      This is an automated message, do not reply.
                    </td>
                  </tr>
                  <tr>
                    <td class='left' width='129' height='20' style='padding-top:10px; text-align:left;'>
                      <p class='left' width='129' height='20' alt='Powered by Altexintel'><i>Powered by {{company.name}}</i></p>
                    </td>
                  </tr>
                </table>

                </td>
              </tr>
            </table>
          </center>
        </td>
      </tr>
    </table>
  </center>
  </td>
</tr>
</table>
</body>
</html>

templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Faq | {{company.name}}</title>
{% endblock %}

{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb text-center">
                    <div class="section-headline white-headline">
                        {% if messages %}
                        {% for message in messages %}
                        <h4 style="color: #fff;">{{message}}</h4>
                        {% endfor %}
                        {% else %}
                        <h3>FAQ</h3>
                        {% endif %}
                    </div>
                    <ul class="breadcrumb-bg">
                        <li class="home-bread">Home</li>
                        <li>FAQ</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->
    <!-- Start FAQ area -->
    <div class="faq-area bg-color page-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="section-headline text-center">
                    <h3>Some important FAQ</h3>
                    <p>Help agencies to define their new business objectives and then create professional software.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Start Column Start -->
            <div class="col-md-7 col-sm-6 col-xs-12">
                <div class="company-faq">
                    <div class="faq-full">
                        <div class="faq-details">
                            <div class="panel-group" id="accordion">
                                <!-- Panel Default -->
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="check-title">
                                            <a data-toggle="collapse" class="active" data-parent="#accordion" href="#check1">
                                                <span class="acc-icons"></span>How to successful our mission and vision
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="check1" class="panel-collapse collapse in">
                                        <div class="panel-body">
                                            <p>
                                                When replacing a multi-lined selection of text, the generated dummy text maintains the amount of lines. When replacing a selection of text within a single line, the amount of words is roughly being maintained. 
                                            </p>		
                                        </div>
                                    </div>
                                </div>
                                <!-- End Panel Default -->
                                <!-- Panel Default -->
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="check-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#check2">
                                                <span class="acc-icons"></span>Clients satisfaction make company Value.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="check2" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>
                                                When replacing a multi-lined selection of text, the generated dummy text maintains the amount of lines. When replacing a selection of text within a single line, the amount of words is roughly being maintained. 
                                            </p>										
                                        </div>
                                    </div>
                                </div>
                                <!-- End Panel Default -->
                                <!-- Panel Default -->
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="check-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#check3">
                                                <span class="acc-icons"></span>World class creative design and development firm. 
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="check3" class="panel-collapse collapse ">
                                        <div class="panel-body">
                                            <p>
                                                When replacing a multi-lined selection of text, the generated dummy text maintains the amount of lines. When replacing a selection of text within a single line, the amount of words is roughly being maintained. 
                                            </p>	
                                        </div>
                                    </div>
                                </div>
                                <!-- End Panel Default -->	
                                <!-- Panel Default -->
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="check-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#check4">
                                                <span class="acc-icons"></span>We are the best online flatform 
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="check4" class="panel-collapse collapse ">
                                        <div class="panel-body">
                                            <p>
                                                When replacing a multi-lined selection of text, the generated dummy text maintains the amount of lines. When replacing a selection of text within a single line, the amount of words is roughly being maintained. 
                                            </p>	
                                        </div>
                                    </div>
                                </div>
                                <!-- End Panel Default -->
                                <!-- Panel Default -->
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="check-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#check5">
                                                <span class="acc-icons"></span>Clients satisfaction make company Value.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="check5" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>
                                                When replacing a multi-lined selection of text, the generated dummy text maintains the amount of lines. When replacing a selection of text within a single line, the amount of words is roughly being maintained. 
                                            </p>										
                                        </div>
                                    </div>
                                </div>
                                <!-- End Panel Default -->										
                            </div>
                        </div>
                        <!-- End FAQ -->
                    </div>
                </div>
            </div>
            <!-- End Column -->
            <div class="col-md-5 col-sm-6 col-xs-12">
                <div class="faq-content">
                    <h4>Have any question?</h4>
                    {% for message in messages %}
                    <h6>{{message}}</h6>
                    {% endfor %}
                    <div class="faq-quote">
                        <div class="row">
                            <form id="contactForm" method="POST" class="contact-form" autocomplete="off">
                                {% csrf_token %}
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="text" maxlength="50" id="name" name="name" class="form-control" placeholder="Name" required data-error="Please enter your name">
                                    <div class="help-block with-errors"></div>
                                    <input type="email" maxlength="50" class="form-control" name="email" id="email" placeholder="Email" required data-error="Please enter your email">
                                    <div class="help-block with-errors"></div>
                                    <input type="text" maxlength="150" id="msg_subject" name="subject" class="form-control" placeholder="Subject" required="" data-error="Please enter your message subject">
                                    <div class="help-block with-errors"></div>
                                    <input type="hidden" maxlength="50" id="location" name="location" class="form-control" placeholder="Location">
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <textarea name="message" maxlength="3500" rows="7" placeholder="Message" class="form-control" required data-error="Write your message"></textarea>
                                    <div class="help-block with-errors"></div>
                                    <button type="submit" name="submit" id="submit" class="quote-btn">Submit</button>
                                    <div id="msgSubmit" class="h3 text-center hidden"></div> 
                                    <div class="clearfix"></div>
                                </div>   
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Column -->
        </div>
    </div>
</div>
<!-- End FAQ area -->
{% endblock %}

{% block script %}
    <!-- Script for getting user timezone/location -->
    <script>
        // Timezone settings
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone; // e.g. "America/New_York"
        console.log(timezone);
        document.getElementById('location').value = timezone;
    </script>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block title %}
<title>Login | {{company.name}}</title>
{% endblock %}


<!-- Mirrored from themes.potenzaglobalsolutions.com/html/mentor-bootstrap-4-admin-dashboard-template/auth-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 21 Jan 2021 00:35:52 GMT -->
<head>
    <title>Login</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="Admin template that can be used to build dashboards for CRM, CMS, etc." />
    <meta name="author" content="Potenza Global Solutions" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- app favicon -->
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <!-- plugin stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors.css' %}" />
    <!-- app style -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
    <style>
        .error {
            color: rgba(211, 14, 14, 0.801);
        }
    </style>
</head>

<body class="bg-white" onunload="">
    <!-- begin app -->
    <div class="app">
        <!-- begin app-wrap -->
        <div class="app-wrap">
            <!-- begin pre-loader -->
            <div class="loader">
                <div class="h-100 d-flex justify-content-center">
                    <div class="align-self-center">
                        <img src="{% static 'assets/img/loader/loader.svg' %}" alt="loader">
                    </div>
                </div>
            </div>
            <!-- end pre-loader -->

            <!--start login contant-->
            <div class="app-contant">
                <div class="bg-white">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters">
                            <div class="col-sm-6 col-lg-5 col-xxl-3  align-self-center order-2 order-sm-1">
                                <div class="d-flex align-items-center h-100-vh">
                                    <div class="login p-50">
                                        <h1 class="mb-2">We Are <span style="text-transform: capitalize;">{{company.name}}</span></h1>
                                        <h5>Welcome back, please login to your account.</h5>
                                        {% for message in messages %}
                                        <p {% if message.tags %}class="{{message.tags}}"{% endif %}>{{message}}</p>
                                        {% endfor %}
                                        <form method="post" class="mt-3 mt-sm-5" autocomplete="off">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="form-group">
                                                        <label class="control-label">Email*</label>
                                                        <input type="email" maxlength="25" name="email" class="form-control" placeholder="Email" />
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-group">
                                                        <label class="control-label">Password*</label>
                                                        <input type="password" maxlength="20" name="password" class="form-control" placeholder="Password" />
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="d-block d-sm-flex  align-items-center">
                                                        <div class="form-check">
                                                            <input class="form-check-input" type="checkbox" id="gridCheck">
                                                            <label class="form-check-label" for="gridCheck">
                                                                Remember Me
                                                            </label>
                                                        </div>
                                                        <a href="{% url 'reset_password' %}" class="ml-auto">Forgot Password ?</a>
                                                    </div>
                                                </div>
                                                <div class="col-12 mt-3">
                                                    <button class="btn btn-primary text-uppercase" name="login-submit">Sign In</button>
                                                </div>
                                                <div class="col-12  mt-3">
                                                    <p>Don't have an account ?<a href="{% url 'mining:register'%}"> Sign Up</a></p>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-xxl-9 col-lg-7 bg-gradient o-hidden order-1 order-sm-2">
                                <div class="row align-items-center h-100">
                                    <div class="col-7 mx-auto ">
                                        <img class="img-fluid" src="{% static 'assets/img/bg/login.svg' %}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end login contant-->
        </div>
        <!-- end app-wrap -->
    </div>
    <!-- end app -->



    <!-- plugins -->
    <script src="{% static 'assets/js/vendors.js' %}"></script>

    <!-- custom app -->
    <script src="{% static 'assets/js/app.js' %}"></script>
</body>


<!-- Mirrored from themes.potenzaglobalsolutions.com/html/mentor-bootstrap-4-admin-dashboard-template/auth-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 21 Jan 2021 00:35:52 GMT -->
</html>